import { readdir, readFile } from "node:fs/promises";
import { dirname, join, posix, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import sidebars from "../sidebars.js";

const docsDir = resolve(dirname(fileURLToPath(import.meta.url)), "../docs");

/** Doc ids of every published page: `.md`/`.mdx` files outside `_`-prefixed paths, honoring frontmatter `id`. */
async function publishedDocIds(dir: string): Promise<Map<string, string>> {
    const ids = new Map<string, string>();
    for (const entry of await readdir(dir, { withFileTypes: true, recursive: true })) {
        if (!entry.isFile() || !/\.mdx?$/.test(entry.name)) continue;
        const file = join(entry.parentPath, entry.name);
        const path = relative(dir, file).split(sep).join("/");
        if (path.split("/").some((segment) => segment.startsWith("_"))) continue;
        const source = await readFile(file, "utf8");
        const frontmatter = /^---\n([\s\S]*?)\n---/.exec(source)?.[1] ?? "";
        const customId = /^id:\s*["']?([^"'\n]+?)["']?\s*$/m.exec(frontmatter)?.[1];
        const base = path.replace(/\.mdx?$/, "");
        ids.set(customId ? posix.join(posix.dirname(base), customId) : base, path);
    }
    return ids;
}

/** Doc ids referenced by a sidebar (doc items, category links and autogenerated directories). */
function sidebarDocIds(items: unknown, ids = new Set<string>(), dirs = new Set<string>()) {
    if (typeof items === "string") {
        ids.add(items);
    } else if (Array.isArray(items)) {
        for (const item of items) sidebarDocIds(item, ids, dirs);
    } else if (items && typeof items === "object") {
        const item = items as Record<string, unknown>;
        if (item.type === "doc" && typeof item.id === "string") ids.add(item.id);
        if (item.type === "autogenerated" && typeof item.dirName === "string") dirs.add(item.dirName);
        const link = item.link as Record<string, unknown> | undefined;
        if (link?.type === "doc" && typeof link.id === "string") ids.add(link.id);
        if (item.type === "category") sidebarDocIds(item.items, ids, dirs);
        if (item.type === undefined) for (const value of Object.values(item)) sidebarDocIds(value, ids, dirs);
    }
    return { ids, dirs };
}

async function main() {
    const published = await publishedDocIds(docsDir);
    const { ids, dirs } = sidebarDocIds(Object.values(sidebars));
    const covered = (id: string) =>
        ids.has(id) || [...dirs].some((dir) => dir === "." || id.startsWith(`${dir}/`));
    const orphans = [...published].filter(([id]) => !covered(id));
    const missing = [...ids].filter((id) => !published.has(id));
    for (const [id, path] of orphans) {
        console.error(`Orphan page: docs/${path} (doc id "${id}") is not referenced from sidebars.ts`);
    }
    for (const id of missing) {
        console.error(`Unknown doc id in sidebars.ts: "${id}"`);
    }
    if (orphans.length > 0 || missing.length > 0) {
        console.error("Add pages to apps/docs/sidebars.ts, or prefix partials with `_` so they are not published.");
        process.exitCode = 1;
        return;
    }
    console.log(`Sidebar check: all ${published.size} pages are referenced from sidebars.ts.`);
}

main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
