import { promises as fs } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildSchemaModel } from "./schema-docs/model.js";
import { schemaDocs } from "./schema-docs/registry.js";

const outputDir = resolve(dirname(fileURLToPath(import.meta.url)), "../docs/_generated/schemas");

/** Write one JSON model per registry entry plus an index module for `<SchemaReference>`. */
async function main() {
    await fs.rm(outputDir, { recursive: true, force: true });
    await fs.mkdir(outputDir, { recursive: true });
    const names = new Set<string>();
    for (const { name, schema } of schemaDocs) {
        if (!/^[a-z0-9-]+$/.test(name) || names.has(name)) {
            throw new Error(`Invalid or duplicate schema docs name: ${name}`);
        }
        names.add(name);
        const model = buildSchemaModel(schema);
        await fs.writeFile(resolve(outputDir, `${name}.json`), `${JSON.stringify(model, null, 2)}\n`, "utf8");
    }
    const imports = [...names].map((name, index) => `import model${index} from "./${name}.json";`);
    const entries = [...names].map((name, index) => `    ${JSON.stringify(name)}: model${index},`);
    const index = [
        "// Auto-generated by apps/docs/scripts/generate-schema-docs.ts. Do not edit.",
        ...imports,
        "",
        "const models: Record<string, unknown> = {",
        ...entries,
        "};",
        "",
        "export default models;",
        "",
    ].join("\n");
    await fs.writeFile(resolve(outputDir, "index.ts"), index, "utf8");
    console.log(`Generated ${names.size} schema model(s) -> ${outputDir}`);
}

main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
